default: &default
  adapter: postgresql
  encoding: unicode
  hostname: localhost
  database: craftcred
  pool: 5
  username: postgres
  password: postgres

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default